In [113]:
import numpy as np
def compute_epsilon_greedy_action_probs(q_vals, epsilon):
    assert len(q_vals.shape) == 1

    if epsilon == 0:
        epsilon += 0.000001
    action_probabilities = np.zeros(q_vals.shape)
    action_probabilities += (epsilon / len(q_vals))

    #if np.isclose(q, q.max()).sum() > 1:
    max_idx = np.random.choice(np.flatnonzero(np.isclose(q, q.max())))
    action_probabilities[max_idx] += 1 - epsilon

    assert action_probabilities.shape == q_vals.shape
    return action_probabilities

def compute_epsilon_greedy_action_probs(q_vals, epsilon):
    assert len(q_vals.shape) == 1

    action_probabilities = np.zeros(q_vals.shape)
    if epsilon != 0:
        action_probabilities += (epsilon / len(q_vals))
    
    action_probabilities = action_probabilities + (np.isclose(q_vals, q_vals.max()) * (1-epsilon) / np.isclose(q_vals, q_vals.max()).sum())

    #max_idx = np.random.choice(np.flatnonzero(np.isclose(q_vals, q_vals.max())))
    #action_probabilities[max_idx] += 1 - epsilon

    assert action_probabilities.shape == q_vals.shape
    return action_probabilities

In [7]:
q = np.random.random(4)
q

array([0.06772318, 0.31683687, 0.7195693 , 0.18245948])

In [22]:
q[0] = 0.7195693
q

array([0.7195693 , 0.31683687, 0.7195693 , 0.18245948])

np.int64(0)

In [119]:

e = 0.1
a = compute_epsilon_greedy_action_probs(q,e)
a, np.sum(a)

(array([0.475, 0.025, 0.475, 0.025]), np.float64(1.0))

In [112]:
v = q + (q * np.isclose(q, q.max()) * (1-e) / np.isclose(q, q.max()).sum())
v

array([0.7195693 , 0.31683687, 0.7195693 , 0.18245948])

In [121]:
!pip install gymnasium

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 958.1/958.1 kB 25.2 MB/s eta 0:00:00


In [122]:
import numpy as np
import gymnasium as gym

class TestEnv(gym.Env):

    def __init__(self):
        self.observation_space = gym.spaces.Discrete(13)
        self.action_space = gym.spaces.Discrete(2)
        self.reset_counter = 0
        self.resets = [0, 3, 6, 9]
        self.termination_obs = [2, 8]
        self.truncation_obs = [5, 12]
        self.current_obs = 0

    def reset(self, seed=None, options=None):
        if self.reset_counter > 0:
            assert self.current_obs == self.resets[self.reset_counter] - 1, f"{self.current_obs} vs {self.resets[self.reset_counter]}"
        observation = self.resets[self.reset_counter]
        self.reset_counter += 1
        self.current_obs = observation
        return observation, {}

    def step(self, action):
        self.current_obs += 1
        terminated = self.current_obs in self.termination_obs
        truncated = self.current_obs in self.truncation_obs
        return self.current_obs, self.current_obs * 0.5, terminated, truncated, {}

class TestAgent:

    def __init__(self):
        self.observation_list = []
        self.reward_list = []
        self.termination_list = []
        self.truncation_list = []

    def act(self, obs: int) -> int:
        return 0

    def process_transition(self, obs: int, reward: float, terminated: bool, truncated: bool) -> None:
        self.observation_list.append(obs)
        self.reward_list.append(reward)
        self.termination_list.append(terminated)
        self.truncation_list.append(truncated)

def test_agent_environment_step_loop():
    try:
        agent = TestAgent()
        env = TestEnv()
        num_timesteps = 8
        episode_rewards = agent_environment.agent_environment_step_loop(agent, env, num_timesteps)
        expected_results = np.array([1.5, 4.5, 7.5])
        actual_result = np.array(episode_rewards)
        test_passed = np.allclose(expected_results, actual_result)
        test_result = "PASSED" if test_passed else "FAILED"
        total_marks = 10
        marks = total_marks if test_passed else 0
    except Exception as e:
        test_result = "FAILED"
        total_marks = 10
        marks = 0
    print(f"test_agent_environment_step_loop: {test_result}. Marks: {marks}/{total_marks}")
    return marks




test_agent_environment_step_loop: FAILED. Marks: 0/10


0

In [129]:

def agent_environment_episode_loop(agent, env, num_episodes):
    episode_returns = []
    for episode in range(num_episodes):
        observation, info = env.reset()
        agent.state = observation
        terminated = False
        truncated = False
        episode_return = 0
        while not (terminated or truncated):
            action = agent.act(observation)
            agent.action = action
            observation, reward, terminated, truncated, info = env.step(action)
            agent.process_transition(observation, reward, terminated, truncated)
            episode_return += reward
        episode_returns.append(episode_return)
    return episode_returns

def agent_environment_step_loop(agent, env, num_steps):
    observation, info = env.reset()
    agent.state = observation
    episode_returns = []
    episode_return = 0
    for _ in range(num_steps):
        action = agent.act(observation)
        agent.action = action
        observation, reward, terminated, truncated, info = env.step(action)
        agent.process_transition(observation, reward, terminated, truncated)
        episode_return += reward
        if terminated or truncated:
            observation, info = env.reset()
            agent.state = observation
            episode_returns.append(episode_return)
            episode_return = 0
    return episode_returns

In [130]:
agent = TestAgent()
env = TestEnv()
num_timesteps = 8
episode_rewards = agent_environment_step_loop(agent, env, num_timesteps)
expected_results = np.array([1.5, 4.5, 7.5])
actual_result = np.array(episode_rewards)
test_passed = np.allclose(expected_results, actual_result)
test_result = "PASSED" if test_passed else "FAILED"
total_marks = 10
marks = total_marks if test_passed else 0
print(f"test_agent_environment_step_loop: {test_result}. Marks: {marks}/{total_marks}")


test_agent_environment_step_loop: PASSED. Marks: 10/10


In [128]:
episode_rewards

[1.5, 6.0, 13.5]